[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
HH_USER_AGENT = "HH-KZ-CAD-Jobs/1.1 (your_email@example.com)"
