name: Setup GitHub Codespaces

on:
  push:
    branches: [ main, master ]

jobs:
  setup-codespaces:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Create .devcontainer configuration
      run: |
        mkdir -p .devcontainer
        cat > .devcontainer/devcontainer.json << 'EOF'
        {
          "name": "HH KZ CAD Jobs",
          "image": "mcr.microsoft.com/devcontainers/python:3.9",
          "features": {
            "ghcr.io/devcontainers/features/git:1": {}
          },
          "customizations": {
            "vscode": {
              "extensions": [
                "ms-python.python",
                "ms-python.vscode-pylance",
                "ms-vscode.vscode-json"
              ]
            }
          },
          "forwardPorts": [8080],
          "postCreateCommand": "pip install -r requirements.txt",
          "postStartCommand": "python app.py"
        }
        EOF
    
    - name: Create launch configuration
      run: |
        mkdir -p .vscode
        cat > .vscode/launch.json << 'EOF'
        {
          "version": "0.2.0",
          "configurations": [
            {
              "name": "Python: FastAPI",
              "type": "python",
              "request": "launch",
              "program": "app.py",
              "console": "integratedTerminal",
              "env": {
                "PORT": "8080"
              }
            }
          ]
        }
        EOF
